export type RailKind = "wallet" | "bank";

export type Rail = {
  id: string;
  name: string;
  kind: RailKind;
  eta: "seconds" | "minutes";
};

export type Region = "West" | "East" | "North" | "Southern" | "Central";

export type Country = {
  iso2: string;
  name: string;
  currency: string;
  currencyName: string;
  region: Region;
  regulator: string;
  rails: Rail[];
  /** Units of local currency per 1 GBP at mid-market, illustrative. */
  gbpRate: number;
};

const WALLET = (id: string, name: string): Rail => ({
  id,
  name,
  kind: "wallet",
  eta: "seconds",
});
const BANK = (name = "Bank account"): Rail => ({
  id: "bank",
  name,
  kind: "bank",
  eta: "minutes",
});

const MTN = WALLET("mtn", "MTN MoMo");
const MPESA = WALLET("mpesa", "M-Pesa");
const ORANGE = WALLET("orange", "Orange Money");
const AIRTEL = WALLET("airtel", "Airtel Money");
const WAVE = WALLET("wave", "Wave");
const TELECEL = WALLET("telecel", "Telecel Cash");
const OPAY = WALLET("opay", "OPay");
const VODACOM = WALLET("vodacom", "Vodacom M-Pesa");
const MOOV = WALLET("moov", "Moov Money");
const FREE = WALLET("free", "Free Money");
const ECOCASH = WALLET("ecocash", "EcoCash");
const TIGO = WALLET("tigo", "Mixx by Yas");
const HALOTEL = WALLET("halotel", "HaloPesa");
const EQUITEL = WALLET("equitel", "Equitel");

export const SEND_CURRENCIES = ["GBP", "USD", "EUR"] as const;
export type SendCurrency = (typeof SEND_CURRENCIES)[number];

export const FX_TO_GBP: Record<SendCurrency, number> = {
  GBP: 1,
  USD: 0.78,
  EUR: 0.86,
};

export const COUNTRIES: Country[] = [
  {
    iso2: "gh",
    name: "Ghana",
    currency: "GHS",
    currencyName: "Cedi",
    region: "West",
    regulator: "Bank of Ghana · PSP",
    rails: [MTN, TELECEL, WALLET("at", "AT Money"), BANK("Ghana bank")],
    gbpRate: 15.16,
  },
  {
    iso2: "ng",
    name: "Nigeria",
    currency: "NGN",
    currencyName: "Naira",
    region: "West",
    regulator: "CBN · IMT",
    rails: [OPAY, WALLET("palmpay", "PalmPay"), AIRTEL, BANK("Nigerian bank")],
    gbpRate: 1924,
  },
  {
    iso2: "ke",
    name: "Kenya",
    currency: "KES",
    currencyName: "Shilling",
    region: "East",
    regulator: "CBK · Money remittance",
    rails: [MPESA, AIRTEL, EQUITEL, BANK("Kenyan bank")],
    gbpRate: 167.4,
  },
  {
    iso2: "za",
    name: "South Africa",
    currency: "ZAR",
    currencyName: "Rand",
    region: "Southern",
    regulator: "SARB · ADLA",
    rails: [WALLET("fnb", "FNB eWallet"), WALLET("capitec", "Capitec Pay"), BANK("South African bank")],
    gbpRate: 23.82,
  },
  {
    iso2: "eg",
    name: "Egypt",
    currency: "EGP",
    currencyName: "Pound",
    region: "North",
    regulator: "CBE · Payment licence",
    rails: [WALLET("vodafone", "Vodafone Cash"), ORANGE, BANK("Egyptian bank")],
    gbpRate: 63.1,
  },
  {
    iso2: "tz",
    name: "Tanzania",
    currency: "TZS",
    currencyName: "Shilling",
    region: "East",
    regulator: "BoT · Payment system",
    rails: [VODACOM, AIRTEL, TIGO, HALOTEL, BANK()],
    gbpRate: 3358,
  },
  {
    iso2: "ug",
    name: "Uganda",
    currency: "UGX",
    currencyName: "Shilling",
    region: "East",
    regulator: "BoU · Payment service",
    rails: [MTN, AIRTEL, BANK()],
    gbpRate: 4752,
  },
  {
    iso2: "rw",
    name: "Rwanda",
    currency: "RWF",
    currencyName: "Franc",
    region: "East",
    regulator: "BNR · Payment service",
    rails: [MTN, AIRTEL, BANK()],
    gbpRate: 1754,
  },
  {
    iso2: "et",
    name: "Ethiopia",
    currency: "ETB",
    currencyName: "Birr",
    region: "East",
    regulator: "NBE · Payment licence",
    rails: [WALLET("telebirr", "Telebirr"), WALLET("cbebirr", "CBE Birr"), BANK()],
    gbpRate: 154.8,
  },
  {
    iso2: "ci",
    name: "Côte d’Ivoire",
    currency: "XOF",
    currencyName: "CFA franc",
    region: "West",
    regulator: "BCEAO · SFD / EMI",
    rails: [ORANGE, MTN, WAVE, MOOV, BANK()],
    gbpRate: 790,
  },
  {
    iso2: "sn",
    name: "Senegal",
    currency: "XOF",
    currencyName: "CFA franc",
    region: "West",
    regulator: "BCEAO · SFD / EMI",
    rails: [WAVE, ORANGE, FREE, BANK()],
    gbpRate: 790,
  },
  {
    iso2: "cm",
    name: "Cameroon",
    currency: "XAF",
    currencyName: "CFA franc",
    region: "Central",
    regulator: "BEAC · Payment service",
    rails: [MTN, ORANGE, BANK()],
    gbpRate: 790,
  },
  {
    iso2: "ma",
    name: "Morocco",
    currency: "MAD",
    currencyName: "Dirham",
    region: "North",
    regulator: "Bank Al-Maghrib",
    rails: [WALLET("inwi", "inwi money"), ORANGE, BANK()],
    gbpRate: 12.84,
  },
  {
    iso2: "tn",
    name: "Tunisia",
    currency: "TND",
    currencyName: "Dinar",
    region: "North",
    regulator: "BCT",
    rails: [WALLET("d17", "D17"), BANK()],
    gbpRate: 3.86,
  },
  {
    iso2: "dz",
    name: "Algeria",
    currency: "DZD",
    currencyName: "Dinar",
    region: "North",
    regulator: "Bank of Algeria",
    rails: [WALLET("baridimob", "BaridiMob"), BANK()],
    gbpRate: 173.2,
  },
  {
    iso2: "ao",
    name: "Angola",
    currency: "AOA",
    currencyName: "Kwanza",
    region: "Southern",
    regulator: "BNA",
    rails: [WALLET("multicaixa", "Multicaixa Express"), BANK()],
    gbpRate: 1184,
  },
  {
    iso2: "mz",
    name: "Mozambique",
    currency: "MZN",
    currencyName: "Metical",
    region: "Southern",
    regulator: "BdM",
    rails: [VODACOM, MPESA, BANK()],
    gbpRate: 82.4,
  },
  {
    iso2: "zm",
    name: "Zambia",
    currency: "ZMW",
    currencyName: "Kwacha",
    region: "Southern",
    regulator: "BoZ",
    rails: [MTN, AIRTEL, BANK()],
    gbpRate: 35.6,
  },
  {
    iso2: "zw",
    name: "Zimbabwe",
    currency: "ZWG",
    currencyName: "ZiG",
    region: "Southern",
    regulator: "RBZ",
    rails: [ECOCASH, WALLET("innbucks", "InnBucks"), BANK()],
    gbpRate: 34.8,
  },
  {
    iso2: "bw",
    name: "Botswana",
    currency: "BWP",
    currencyName: "Pula",
    region: "Southern",
    regulator: "Bank of Botswana",
    rails: [ORANGE, BANK()],
    gbpRate: 17.6,
  },
  {
    iso2: "na",
    name: "Namibia",
    currency: "NAD",
    currencyName: "Dollar",
    region: "Southern",
    regulator: "BON",
    rails: [WALLET("nampay", "PayToday"), BANK()],
    gbpRate: 23.82,
  },
  {
    iso2: "mw",
    name: "Malawi",
    currency: "MWK",
    currencyName: "Kwacha",
    region: "Southern",
    regulator: "RBM",
    rails: [AIRTEL, TIGO, BANK()],
    gbpRate: 2240,
  },
  {
    iso2: "mg",
    name: "Madagascar",
    currency: "MGA",
    currencyName: "Ariary",
    region: "Southern",
    regulator: "BFM",
    rails: [ORANGE, AIRTEL, BANK()],
    gbpRate: 5880,
  },
  {
    iso2: "mu",
    name: "Mauritius",
    currency: "MUR",
    currencyName: "Rupee",
    region: "Southern",
    regulator: "BoM",
    rails: [WALLET("juice", "Juice"), BANK()],
    gbpRate: 59.4,
  },
  {
    iso2: "ls",
    name: "Lesotho",
    currency: "LSL",
    currencyName: "Loti",
    region: "Southern",
    regulator: "CBL",
    rails: [ECOCASH, MPESA, BANK()],
    gbpRate: 23.82,
  },
  {
    iso2: "sz",
    name: "Eswatini",
    currency: "SZL",
    currencyName: "Lilangeni",
    region: "Southern",
    regulator: "CBE",
    rails: [MTN, BANK()],
    gbpRate: 23.82,
  },
  {
    iso2: "bj",
    name: "Benin",
    currency: "XOF",
    currencyName: "CFA franc",
    region: "West",
    regulator: "BCEAO",
    rails: [MTN, MOOV, BANK()],
    gbpRate: 790,
  },
  {
    iso2: "bf",
    name: "Burkina Faso",
    currency: "XOF",
    currencyName: "CFA franc",
    region: "West",
    regulator: "BCEAO",
    rails: [ORANGE, MOOV, BANK()],
    gbpRate: 790,
  },
  {
    iso2: "ml",
    name: "Mali",
    currency: "XOF",
    currencyName: "CFA franc",
    region: "West",
    regulator: "BCEAO",
    rails: [ORANGE, MOOV, BANK()],
    gbpRate: 790,
  },
  {
    iso2: "ne",
    name: "Niger",
    currency: "XOF",
    currencyName: "CFA franc",
    region: "West",
    regulator: "BCEAO",
    rails: [AIRTEL, MOOV, BANK()],
    gbpRate: 790,
  },
  {
    iso2: "tg",
    name: "Togo",
    currency: "XOF",
    currencyName: "CFA franc",
    region: "West",
    regulator: "BCEAO",
    rails: [TIGO, MOOV, WALLET("flooz", "Flooz"), BANK()],
    gbpRate: 790,
  },
  {
    iso2: "gn",
    name: "Guinea",
    currency: "GNF",
    currencyName: "Franc",
    region: "West",
    regulator: "BCRG",
    rails: [ORANGE, MTN, BANK()],
    gbpRate: 11140,
  },
  {
    iso2: "gw",
    name: "Guinea-Bissau",
    currency: "XOF",
    currencyName: "CFA franc",
    region: "West",
    regulator: "BCEAO",
    rails: [ORANGE, BANK()],
    gbpRate: 790,
  },
  {
    iso2: "gm",
    name: "Gambia",
    currency: "GMD",
    currencyName: "Dalasi",
    region: "West",
    regulator: "CBG",
    rails: [WALLET("afrimoney", "Afrimoney"), BANK()],
    gbpRate: 92.4,
  },
  {
    iso2: "sl",
    name: "Sierra Leone",
    currency: "SLE",
    currencyName: "Leone",
    region: "West",
    regulator: "BSL",
    rails: [WALLET("africell", "Africell Money"), ORANGE, BANK()],
    gbpRate: 29.8,
  },
  {
    iso2: "lr",
    name: "Liberia",
    currency: "LRD",
    currencyName: "Dollar",
    region: "West",
    regulator: "CBL",
    rails: [ORANGE, MTN, BANK()],
    gbpRate: 255,
  },
  {
    iso2: "cv",
    name: "Cabo Verde",
    currency: "CVE",
    currencyName: "Escudo",
    region: "West",
    regulator: "BCV",
    rails: [WALLET("cvmovel", "CVMóvel"), BANK()],
    gbpRate: 132.4,
  },
  {
    iso2: "cd",
    name: "DR Congo",
    currency: "CDF",
    currencyName: "Franc",
    region: "Central",
    regulator: "BCC",
    rails: [VODACOM, ORANGE, AIRTEL, BANK()],
    gbpRate: 3680,
  },
  {
    iso2: "cg",
    name: "Congo",
    currency: "XAF",
    currencyName: "CFA franc",
    region: "Central",
    regulator: "BEAC",
    rails: [MTN, AIRTEL, BANK()],
    gbpRate: 790,
  },
  {
    iso2: "ga",
    name: "Gabon",
    currency: "XAF",
    currencyName: "CFA franc",
    region: "Central",
    regulator: "BEAC",
    rails: [AIRTEL, MOOV, BANK()],
    gbpRate: 790,
  },
  {
    iso2: "td",
    name: "Chad",
    currency: "XAF",
    currencyName: "CFA franc",
    region: "Central",
    regulator: "BEAC",
    rails: [AIRTEL, MOOV, BANK()],
    gbpRate: 790,
  },
  {
    iso2: "cf",
    name: "Central African Republic",
    currency: "XAF",
    currencyName: "CFA franc",
    region: "Central",
    regulator: "BEAC",
    rails: [ORANGE, BANK()],
    gbpRate: 790,
  },
  {
    iso2: "gq",
    name: "Equatorial Guinea",
    currency: "XAF",
    currencyName: "CFA franc",
    region: "Central",
    regulator: "BEAC",
    rails: [WALLET("muni", "Muni Dinero"), BANK()],
    gbpRate: 790,
  },
  {
    iso2: "st",
    name: "São Tomé and Príncipe",
    currency: "STN",
    currencyName: "Dobra",
    region: "Central",
    regulator: "BCSTP",
    rails: [BANK()],
    gbpRate: 29.4,
  },
  {
    iso2: "bi",
    name: "Burundi",
    currency: "BIF",
    currencyName: "Franc",
    region: "East",
    regulator: "BRB",
    rails: [WALLET("lumicash", "Lumicash"), ECOCASH, BANK()],
    gbpRate: 3780,
  },
  {
    iso2: "ss",
    name: "South Sudan",
    currency: "SSP",
    currencyName: "Pound",
    region: "East",
    regulator: "BoSS",
    rails: [MTN, BANK()],
    gbpRate: 4210,
  },
  {
    iso2: "sd",
    name: "Sudan",
    currency: "SDG",
    currencyName: "Pound",
    region: "North",
    regulator: "CBOS",
    rails: [WALLET("bankak", "Bankak"), BANK()],
    gbpRate: 768,
  },
  {
    iso2: "so",
    name: "Somalia",
    currency: "SOS",
    currencyName: "Shilling",
    region: "East",
    regulator: "CBS",
    rails: [WALLET("evc", "EVC Plus"), WALLET("zaad", "Zaad"), BANK()],
    gbpRate: 738,
  },
  {
    iso2: "dj",
    name: "Djibouti",
    currency: "DJF",
    currencyName: "Franc",
    region: "East",
    regulator: "BCD",
    rails: [WALLET("dmoney", "D-Money"), BANK()],
    gbpRate: 229.4,
  },
  {
    iso2: "er",
    name: "Eritrea",
    currency: "ERN",
    currencyName: "Nakfa",
    region: "East",
    regulator: "Bank of Eritrea",
    rails: [BANK()],
    gbpRate: 19.4,
  },
  {
    iso2: "ly",
    name: "Libya",
    currency: "LYD",
    currencyName: "Dinar",
    region: "North",
    regulator: "CBL",
    rails: [WALLET("lypay", "Moamalat"), BANK()],
    gbpRate: 6.94,
  },
  {
    iso2: "mr",
    name: "Mauritania",
    currency: "MRU",
    currencyName: "Ouguiya",
    region: "North",
    regulator: "BCM",
    rails: [BANK(), WALLET("bankily", "Bankily")],
    gbpRate: 51.2,
  },
  {
    iso2: "km",
    name: "Comoros",
    currency: "KMF",
    currencyName: "Franc",
    region: "East",
    regulator: "BCC",
    rails: [BANK()],
    gbpRate: 575,
  },
  {
    iso2: "sc",
    name: "Seychelles",
    currency: "SCR",
    currencyName: "Rupee",
    region: "East",
    regulator: "CBS",
    rails: [BANK()],
    gbpRate: 18.6,
  },
];

export const COUNTRY_BY_ISO = Object.fromEntries(COUNTRIES.map((c) => [c.iso2, c])) as Record<
  string,
  Country
>;

export function countryByIso(iso2: string) {
  return COUNTRY_BY_ISO[iso2.toLowerCase()];
}

export function flagUrl(iso2: string, width = 80) {
  return `https://flagcdn.com/w${width}/${iso2.toLowerCase()}.png`;
}

export const REGIONS: Region[] = ["West", "East", "North", "Southern", "Central"];
