/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppActivityRouteImport } from './routes/_app/activity'
import { Route as AppPeopleRouteImport } from './routes/_app/people'
import { Route as AppPulseRouteImport } from './routes/_app/pulse'
import { Route as AppSendRouteImport } from './routes/_app/send'
import { Route as AppYouRouteImport } from './routes/_app/you'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleRoute = AppPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRoute,
} as any)
const AppPulseRoute = AppPulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => AppRoute,
} as any)
const AppSendRoute = AppSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AppRoute,
} as any)
const AppYouRoute = AppYouRouteImport.update({
  id: '/you',
  path: '/you',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/activity': typeof AppActivityRoute
  '/people': typeof AppPeopleRoute
  '/pulse': typeof AppPulseRoute
  '/send': typeof AppSendRoute
  '/you': typeof AppYouRoute
}
export interface FileRoutesByTo {
  '/activity': typeof AppActivityRoute
  '/people': typeof AppPeopleRoute
  '/pulse': typeof AppPulseRoute
  '/send': typeof AppSendRoute
  '/you': typeof AppYouRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/activity': typeof AppActivityRoute
  '/_app/people': typeof AppPeopleRoute
  '/_app/pulse': typeof AppPulseRoute
  '/_app/send': typeof AppSendRoute
  '/_app/you': typeof AppYouRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/activity' | '/people' | '/pulse' | '/send' | '/you'
  fileRoutesByTo: FileRoutesByTo
  to: '/activity' | '/people' | '/pulse' | '/send' | '/you' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/activity'
    | '/_app/people'
    | '/_app/pulse'
    | '/_app/send'
    | '/_app/you'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people': {
      id: '/_app/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AppPeopleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pulse': {
      id: '/_app/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof AppPulseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/send': {
      id: '/_app/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof AppSendRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/you': {
      id: '/_app/you'
      path: '/you'
      fullPath: '/you'
      preLoaderRoute: typeof AppYouRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppPeopleRoute: typeof AppPeopleRoute
  AppPulseRoute: typeof AppPulseRoute
  AppSendRoute: typeof AppSendRoute
  AppYouRoute: typeof AppYouRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppPeopleRoute: AppPeopleRoute,
  AppPulseRoute: AppPulseRoute,
  AppSendRoute: AppSendRoute,
  AppYouRoute: AppYouRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
